export const path = {
    home: '/',
    login: '/login',
    MyBookings: '/my-bookings',
    profile: '/profile',
    wallets: '/wallets',
    venue: '/venue/:venueId',
    venueAbout: '/venue/:venueId/about',
    venuePoints: '/venue/:venueId/points',
    booking: '/booking/:facilityId/:courtId?',
    confirmBooking: '/confirm-booking',
    multiConfirmBooking: '/multi-confirm-booking',
    bookingSuccess: '/booking-success',
    events: '/events',
    eventRegister: '/events/:slug/register',
    eventPass: '/events/:slug/pass',
    eventHosts: '/events/:slug/hosts',
    eventRules: '/events/:slug/rules',
    eventPlayers: '/events/:slug/players',
    eventStandings: '/events/:slug/standings',
    eventDetail: '/events/:slug',
};
